name: $plugin_id
description: "Plugin Library for sylviameows' plugins."

version: $plugin_version
api-version: $api_version

main: net.sylviameows.kitti.Core
bootstrapper: net.sylviameows.kitti.Bootstrap

load: STARTUP

author: sylviameows
website: "https://sylviameo.ws/projects/kitti"



